meta_product_name: "Learn Better"
meta_title: "Learn Better - Learn more, faster, better."
meta_description: "Simple smart flashcards that help you learn more, faster, better."
meta_image: "flig.jpg"
